import { createServer } from 'node:http';
import { existsSync, readFileSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const rootDir = dirname(fileURLToPath(import.meta.url));
const distDir = join(rootDir, 'dist');
const curatedVocabularyPath = join(rootDir, 'data', 'ielts_curated_words.json');
const expandedVocabularyPath = join(rootDir, 'data', 'ielts_5000_words.json');
const port = Number(process.env.API_PORT ?? 4174);
const defaultUserId = 1;

const pool = new pg.Pool({
  host: process.env.PGHOST ?? '127.0.0.1',
  port: Number(process.env.PGPORT ?? 5432),
  user: process.env.PGUSER ?? 'codex',
  password: process.env.PGPASSWORD ?? 'codex',
  database: process.env.PGDATABASE ?? 'codex_dev',
  max: 10,
});

await connectWithRetry();
await initPostgres();

const server = createServer(async (request, response) => {
  try {
    if (!request.url) return send(response, 404, { error: 'Not found' });
    const url = new URL(request.url, `http://${request.headers.host}`);

    if (request.method === 'OPTIONS') {
      return send(response, 204, {});
    }

    if (request.method === 'GET' && url.pathname === '/api/bootstrap') {
      return send(response, 200, await getBootstrap());
    }

    if (request.method === 'PATCH' && url.pathname === '/api/user') {
      const body = await readJson(request);
      return send(response, 200, { user: await updateUser(body) });
    }

    if (request.method === 'POST' && url.pathname === '/api/progress') {
      const body = await readJson(request);
      return send(response, 200, { progress: await updateProgress(Number(body.wordId), Boolean(body.correct)) });
    }

    if (request.method === 'POST' && url.pathname === '/api/progress/reset') {
      await pool.query('DELETE FROM user_word_progress WHERE user_id = $1', [defaultUserId]);
      await pool.query('INSERT INTO study_sessions (user_id, action, created_at) VALUES ($1, $2, $3)', [
        defaultUserId,
        'reset',
        new Date().toISOString(),
      ]);
      return send(response, 200, { ok: true });
    }

    if (request.method === 'GET') {
      return serveStatic(url.pathname, response);
    }

    return send(response, 404, { error: 'Not found' });
  } catch (error) {
    console.error(error);
    return send(response, 500, { error: error instanceof Error ? error.message : 'Internal server error' });
  }
});

server.listen(port, () => {
  console.log(`Lexora API listening on http://localhost:${port}`);
  console.log(`PostgreSQL database: ${pool.options.host}:${pool.options.port}/${pool.options.database}`);
});

process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);

async function connectWithRetry() {
  const maxAttempts = Number(process.env.PG_CONNECT_ATTEMPTS ?? 30);
  for (let attempt = 1; attempt <= maxAttempts; attempt += 1) {
    try {
      const client = await pool.connect();
      client.release();
      return;
    } catch (error) {
      if (attempt === maxAttempts) throw error;
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }
  }
}

async function initPostgres() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER PRIMARY KEY,
      name TEXT NOT NULL,
      target_band TEXT NOT NULL DEFAULT '7.0',
      daily_target INTEGER NOT NULL DEFAULT 12,
      created_at TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL
    );

    CREATE TABLE IF NOT EXISTS words (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      word TEXT NOT NULL UNIQUE,
      phonetic TEXT NOT NULL,
      pos TEXT NOT NULL,
      meaning TEXT NOT NULL,
      english TEXT NOT NULL,
      example TEXT NOT NULL,
      example_cn TEXT NOT NULL,
      collocations TEXT[] NOT NULL,
      synonyms TEXT[] NOT NULL,
      topic TEXT NOT NULL,
      level TEXT NOT NULL CHECK (level IN ('基础', '高频', '进阶')),
      source TEXT NOT NULL DEFAULT 'IELTS academic high-frequency seed',
      created_at TIMESTAMPTZ NOT NULL
    );

    CREATE TABLE IF NOT EXISTS user_word_progress (
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      word_id INTEGER NOT NULL REFERENCES words(id) ON DELETE CASCADE,
      status TEXT NOT NULL CHECK (status IN ('new', 'learning', 'mastered')),
      seen INTEGER NOT NULL DEFAULT 0,
      correct INTEGER NOT NULL DEFAULT 0,
      last_seen TIMESTAMPTZ NOT NULL,
      updated_at TIMESTAMPTZ NOT NULL,
      PRIMARY KEY (user_id, word_id)
    );

    CREATE TABLE IF NOT EXISTS study_sessions (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      word_id INTEGER REFERENCES words(id) ON DELETE SET NULL,
      action TEXT NOT NULL,
      correct INTEGER,
      created_at TIMESTAMPTZ NOT NULL
    );
  `);

  const now = new Date().toISOString();
  await pool.query(
    `INSERT INTO users (id, name, target_band, daily_target, created_at, updated_at)
     VALUES ($1, $2, $3, $4, $5, $5)
     ON CONFLICT (id) DO NOTHING`,
    [defaultUserId, 'IELTS Learner', '7.0', 12, now],
  );

  await seedVocabulary();
}

async function seedVocabulary() {
  const words = [
    ...loadVocabulary(curatedVocabularyPath),
    ...loadVocabulary(expandedVocabularyPath),
  ];
  if (!words.length) return;

  const client = await pool.connect();
  const now = new Date().toISOString();
  try {
    await client.query('BEGIN');
    for (const word of words) {
      await client.query(
        `INSERT INTO words
          (word, phonetic, pos, meaning, english, example, example_cn, collocations, synonyms, topic, level, source, created_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8::text[], $9::text[], $10, $11, $12, $13)
         ON CONFLICT (word) DO NOTHING`,
        [
          word.word,
          word.phonetic,
          word.pos,
          word.meaning,
          word.english,
          word.example,
          word.exampleCn,
          word.collocations,
          word.synonyms,
          word.topic,
          word.level,
          word.source ?? (word.word.length > 0 ? 'IELTS PostgreSQL vocabulary seed' : 'IELTS vocabulary seed'),
          now,
        ],
      );
    }
    await client.query('COMMIT');
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

function loadVocabulary(path) {
  if (!existsSync(path)) return [];

  const words = JSON.parse(readFileSync(path, 'utf8'));
  if (!Array.isArray(words)) return [];

  const source = path.endsWith('ielts_curated_words.json')
    ? 'IELTS academic curated seed'
    : 'Oxford/Common English + WordNet generated IELTS expansion';

  return words.map((word) => ({ ...word, source }));
}

async function getBootstrap() {
  const userResult = await pool.query('SELECT * FROM users WHERE id = $1', [defaultUserId]);
  const rows = await pool.query(
    `SELECT
      w.*,
      COALESCE(p.status, 'new') AS status,
      COALESCE(p.seen, 0) AS seen,
      COALESCE(p.correct, 0) AS correct,
      COALESCE(p.last_seen::text, '') AS last_seen
     FROM words w
     LEFT JOIN user_word_progress p ON p.word_id = w.id AND p.user_id = $1
     ORDER BY w.id ASC`,
    [defaultUserId],
  );

  return { user: rowToUser(userResult.rows[0]), words: rows.rows.map(rowToWord) };
}

async function updateUser(body) {
  const name = String(body.name ?? '').trim().slice(0, 40) || 'IELTS Learner';
  const targetBand = String(body.targetBand ?? '7.0').trim().slice(0, 8) || '7.0';
  const dailyTarget = Math.min(80, Math.max(1, Number(body.dailyTarget) || 12));
  const now = new Date().toISOString();
  const result = await pool.query(
    `UPDATE users
     SET name = $1, target_band = $2, daily_target = $3, updated_at = $4
     WHERE id = $5
     RETURNING *`,
    [name, targetBand, dailyTarget, now, defaultUserId],
  );

  return rowToUser(result.rows[0]);
}

async function updateProgress(wordId, correct) {
  const word = await pool.query('SELECT id FROM words WHERE id = $1', [wordId]);
  if (!word.rowCount) throw new Error('Word not found');

  const existing = await pool.query('SELECT * FROM user_word_progress WHERE user_id = $1 AND word_id = $2', [
    defaultUserId,
    wordId,
  ]);
  const current = existing.rows[0] ?? { seen: 0, correct: 0 };
  const seen = Number(current.seen) + 1;
  const right = Number(current.correct) + (correct ? 1 : 0);
  const status = correct && seen >= 2 && right / seen >= 0.7 ? 'mastered' : 'learning';
  const now = new Date().toISOString();

  await pool.query(
    `INSERT INTO user_word_progress (user_id, word_id, status, seen, correct, last_seen, updated_at)
     VALUES ($1, $2, $3, $4, $5, $6, $6)
     ON CONFLICT (user_id, word_id) DO UPDATE SET
       status = EXCLUDED.status,
       seen = EXCLUDED.seen,
       correct = EXCLUDED.correct,
       last_seen = EXCLUDED.last_seen,
       updated_at = EXCLUDED.updated_at`,
    [defaultUserId, wordId, status, seen, right, now],
  );

  await pool.query(
    'INSERT INTO study_sessions (user_id, word_id, action, correct, created_at) VALUES ($1, $2, $3, $4, $5)',
    [defaultUserId, wordId, 'review', correct ? 1 : 0, now],
  );

  return { status, seen, correct: right, lastSeen: now };
}

function rowToUser(row) {
  return {
    id: row.id,
    name: row.name,
    targetBand: row.target_band,
    dailyTarget: row.daily_target,
  };
}

function rowToWord(row) {
  return {
    id: row.id,
    word: row.word,
    phonetic: row.phonetic,
    pos: row.pos,
    meaning: row.meaning,
    english: row.english,
    example: row.example,
    exampleCn: row.example_cn,
    collocations: row.collocations,
    synonyms: row.synonyms,
    topic: row.topic,
    level: row.level,
    progress: {
      status: row.status,
      seen: Number(row.seen),
      correct: Number(row.correct),
      lastSeen: row.last_seen,
    },
  };
}

function send(response, status, payload) {
  response.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'GET,POST,PATCH,OPTIONS',
  });

  if (status === 204) {
    response.end();
    return;
  }

  response.end(JSON.stringify(payload));
}

async function serveStatic(pathname, response) {
  const cleanPath = pathname === '/' ? '/index.html' : pathname;
  const filePath = join(distDir, cleanPath);
  const safePath = filePath.startsWith(distDir) ? filePath : join(distDir, 'index.html');
  const targetPath = existsSync(safePath) ? safePath : join(distDir, 'index.html');

  if (!existsSync(targetPath)) {
    return send(response, 404, { error: 'Build output not found. Run npm run build first.' });
  }

  const content = await readFile(targetPath);
  response.writeHead(200, { 'Content-Type': contentType(targetPath) });
  response.end(content);
}

function contentType(path) {
  if (path.endsWith('.html')) return 'text/html; charset=utf-8';
  if (path.endsWith('.js')) return 'text/javascript; charset=utf-8';
  if (path.endsWith('.css')) return 'text/css; charset=utf-8';
  if (path.endsWith('.svg')) return 'image/svg+xml';
  if (path.endsWith('.png')) return 'image/png';
  if (path.endsWith('.jpg') || path.endsWith('.jpeg')) return 'image/jpeg';
  return 'application/octet-stream';
}

async function readJson(request) {
  const chunks = [];
  for await (const chunk of request) {
    chunks.push(chunk);
  }
  const text = Buffer.concat(chunks).toString('utf8');
  return text ? JSON.parse(text) : {};
}

async function shutdown() {
  await pool.end();
  process.exit(0);
}
